# Generated by Django 3.2.8 on 2021-10-15 05:08

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('descripcion_corta', models.CharField(max_length=100, verbose_name='Descripción corta')),
                ('etapa', models.CharField(choices=[('Planeación', 'Planeación'), ('Desarrollo', 'Desarrollo'), ('Despliegue', 'Despliegue'), ('Producción', 'Producción')], max_length=100, verbose_name='Etapa')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Información completa')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_imagen', models.URLField()),
                ('url', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
