# Generated by Django 3.2.8 on 2021-10-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211018_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.AlterModelOptions(
            name='mensajes',
            options={'verbose_name_plural': 'Mensajes'},
        ),
    ]
