# Generated by Django 3.2.8 on 2021-10-19 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_newsletter_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajesProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombreProyecto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensaje', models.TextField(blank=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Mensajes por proyecto',
            },
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Proyecto activo'),
        ),
    ]
